#+TITLE: Reinforcement Learning Portfolio Optimization of Electric Vehicle Virtual Power Plants
#+AUTHOR:Tobias Richter

# Formatting
#+LATEX_CLASS_OPTIONS: [12pt, article]
#+LATEX_HEADER: \usepackage[a4paper, left=5cm,right=2cm,top=2cm,bottom=2cm]{geometry}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage{caption}
#+LATEX_HEADER: \onehalfspacing
#+OPTIONS: H:4

# Typography
#+LATEX_HEADER: \usepackage[official]{eurosym}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}


# Bibliography
#+LATEX_HEADER: \usepackage[backend=biber, style=apa]{biblatex}
#+LATEX_HEADER: \addbibresource{~/uni/ma-thesis/bibliography/references.bib}

# Title & TOC
#+OPTIONS: title:nil toc:nil
#+LATEX_HEADER: \usepackage[numbib,notlof,notlot,nottoc]{tocbibind}
#+LATEX_HEADER: \pagenumbering{Roman}

#+INCLUDE: "~/uni/ma-thesis/titlepage.tex" export latex
#+LATEX: \setcounter{page}{2}

#+LATEX: \tableofcontents
#+LATEX: \clearpage
#+LATEX: \pagenumbering{arabic}

* Introduction (10%)
** Research Motivation
- cite:lopes11_integ_elect_vehic_elect_power_system
# It is also expected that the amount of intermittent RES
# that can be safely integrated into the electric power system
# may increase due to EV storage capacity [11]. Given the
# uncontrollability of these energy sources, since they only
# produce energy when the primary renewable resource is
# available, EV capability to store energy and inject it later
# into the system will avoid spillage of clean energy,
# resulting in the decreased usage of the conventional fossil
# fuel units and expensive generators during peak hours.
** Research Question
** Relevance

#+LATEX: \clearpage
* Related Literature (10%)
** Smart Charging and Balancing the Electric Grid with EV Fleets
# NOTE: Section General Problem and Intro of Smart Charging
The increasing penetration of EVs has a substantial effect on electricity consumption
patterns. During charging periods, power flows and grid losses increase
considerably and challenge the grid. Operators have to reinforce the grid
to ensure that transformers and substations do not get overloaded
parencite:sioshansi12_impac_elect_tarif_plug_in,lopes11_integ_elect_vehic_elect_power_system.
Loading multiple EVs in the same neighbourhood, or worse, whole EV fleets at
once, stress the grid. In these cases, even brown- or blackouts are possible
parencite:kim12_carbit. Despite these challenges, it is possible to postpone the
physical reinforcement by adopting smart charging strategies. In smart charging,
EVs get charged when the grid is less congested to achieve more grid stability.
Smart charging reduces peaks in electricity demand, called /Peak Cutting/ and
complement the grid in times of low demand, called /Valley Filling/. Smart
charging has been researched thoroughly in the IS literature.

# NOTE: Section Smart charging examples and studies
textcite:valogianni14_effec_manag_elect_vehic_storag find that using intelligent
agents to schedule EV charging, substantially reshapes the energy demand and
reduces peak demand without violating individual household preferences. Moreover,
they show that the proposed smart charging behaviour reduced average energy
prices and thus economically benefit households. In another study
textcite:kara15_estim_benef_elect_vehic_smart investigate the effect of smart
charging on public charging stations in California. Controlling for
arrival and departure times, the authors present beneficial results for the
distribution system operator (DSO) and the owners of EVs. A price
reduction in energy bills and a peak load reduction could be determined.
An extension of the smart charging concept is Vehicle-to-Grid (V2G). When
equipped with V2G devices, EVs can discharge their batteries back into the grid.
Several authors conduct research on this technology in respect to grid stabilization
effects and arbitrage possibilities.
textcite:schill11_elect_vehic_imper_elect_market find that EVs can be beneficial
for average consumer electricity prices when the EVs can be used as storage.
Excess EV battery capacity can be used to charge in off-peak hours and discharge
in peak hours, when the prices are higher. These arbitrage possibilities,
reverses welfare effects of generators and increases general overall welfare and
consumer surplus. textcite:tomic07_using_fleet_elect_drive_vehic_grid_suppor
show that the arbitrage opportunities are especially prominent when a high
variability in electricity prices on the target electricity market exists. The
authors state that short intervals between the contract of sale and the physical
delivery of electricity increase arbitrage benefits. Consequently ancillary service
markets, like frequency control and operating reserve markets are attractive for
smart charging.

# NOTE: Section Not looking at V2G. Explain and prove why leaving out V2G.
textcite:peterson10_econom_using_plug_in_hybrid investigate energy arbitrage
profitability with V2G in the light of battery depreciation costs in the US.
Their results indicate that large-scale use of EV batteries for grid storage
does not yield enough profits to incentivize owners to participate in V2G
activities. Considering battery depreciation cost they arrive at an annual
profit of only 6\dollar - 72\dollar per EV.
textcite:brandt17_evaluat_busin_model_vehic_grid_integ evaluated a business
model for parking garage operators operating on the German frequency regulation
market. When taking infrastructure costs and battery depreciation costs into
account they concluded that the proposed vehicle-grid integration is not
profitable. Even with generous assumptions about EV adoption rates in Germany
and altered auction mechanisms they arrived at negative profits.
parencite:kahlen17_fleet used EV fleets to offer balancing services to the grid.
Evaluating the impact of V2G in their model the authors come to the conclusion
that V2G would only be profitable if reserve power prices would be twice as
high. Given the results from the aforementioned studies, we decided not to
include V2G into our model, since expected profits are, at most, marginal.

# NOTE: Section Trading strategies on multiple markets, battery depreciation
To maximize profits, it is essential for market participants to develop good
bidding strategies. Successful bidding strategies to jointly participate in
multiple markets have been developed e.g. by
textcite:mashhour11_biddin_strat_virtual_power_plant_2. The authors use VPPs of
stationary battery storage to participate in the spinning reserve market and
the day-ahead market at the same time. They developed a non-equilibrium model,
which solves the presented mixed-integer program with Genetic Programming (GP).
Contrarily, we use a model-free RL agent that learns an optimal policy (i.e.
trading strategy) from actions it takes in the environment (i.e. bidding on
electricity markets). Using a model-free approach is especially beneficial for
us, since additional unknown variables and constraints (i.e. customer mobility
demand), makes it very hard to formulate a mathematical model.
# TODO: Revise above paragraph, more clarity and concise
Similar research to textcite:mashhour11_biddin_strat_virtual_power_plant_2 has
been done by textcite:he16_optim_biddin_strat_batter_storag. The authors
additionally incorporate battery life cycle in their profit maximization model,
which proves to be a decisive factor. In contrast to the authors, we jointly
participated in the secondary operating reserve and spot market with the
/non-stationary/ storage of EV batteries. Because shared EVs have to satisfy
mobility demands, they have to be charged nonetheless, which allows us to safely
exclude battery deprecation from our model. Further, we choose the intraday
continuous market over the day-ahead market, as it has the lowest reaction time
of the spot markets, and thus offers potentially higher profits
parencite:tomic07_using_fleet_elect_drive_vehic_grid_suppor.

# NOTE: Section Intelligent Agents within Smart Charging
# TODO: Extend section on intelligent agents and electricity brokers, state that
# we are applying this concept with VPP on top.
Previous studies often assume that car owners or households can directly trade
on electricity markets. In reality, this is not possible due to minimum capacity
requirements of the market or reliability requirements for i.e.
regulation capacity, that single EVs do not meet. For example, the German
Control Reserve Market (GCRM) has 1MW to 5MW minimum trading capacity, depending
on the specific market. In order to reach the minimum capacity, over 200 EVs
would need to be connected to a the grid via a normal 4.6kW charging station at
the same time. textcite:ketter13_power_tac introduced the notion of electricity brokers,
aggregators that act on behalf of a group of individuals or households to
participate in electricity markets.
textcite:brandt17_evaluat_busin_model_vehic_grid_integ and
textcite:kahlen14_balan_with_elect_vehic successfully showed in simulations that
electricity brokers can overcome the capacity issues by aggregating distributed
electricity sources.

# NOTE: Section Carsharing and EV fleets
Carsharing providers which manage large EV fleets, can use their vehicles as
VPPs to participate in electricity markets. We look at the concept of free float
carsharing, an approach which offers more flexibility to its users, saves
resources and reduces carbon emissions
parencite:firnkorn15_free_float_elect_carsh_fleet_smart_cities. In most previous
studies concerning using EVs for electricity trading, it was assumed that trips
are fixed and known in advance. The free float concept adds uncertainty and
nondeterministic behavior, as cars can be picked up and parked everywhere and
billing is done by the minute. This makes predictions about the where and when
of a car rental a complex issue. textcite:wagner16_in_free_float address this
problem by taking Points of Interests from Google Maps as an additional
predictor.
# But we....

# NOTE: Section Kahlen in more detail and what we'll do differently
textcite:tomic07_using_fleet_elect_drive_vehic_grid_suppor,kahlen17_fleet showed
that is possible to use free floating carsharing fleets as VPPs to profitably
offer balancing services to the grid. The authors also showed that with a
similar approach, carsharing companies can participate in day-ahead markets for
arbitrage purposes parencite:kahlen18_elect_vehic_virtual_power_plant_dilem. A
central dilemma within this research is to decide whether an EV should be
committed to being used as a VPP or to be free for rent. Rental
profits are considerably higher than profits to be made from electricity
trading.

# - So you don't want to allocate a EV to VPP when it could have been rented out
# - A central point are  the prediction are made on a aggregated fleet level, how
#   much capacity you want to trade
# - Allocations are then made on likelihood that a Car is rented out and expected
#   benefits

Another central problem is that offering capacity to the grid, which
you can not provide, results in heavy penalties, which should be avoided at all
costs. To address this issue, the authors make use of asymmetric objective
functions that heavily penalize committing an EV to a VPP, when it would have
been rented otherwise. Therefore only very conservative estimations and
commitments of available overall capacity to be traded on the markets are made.
This results in a high amount of foregone profits when bidding on the balancing
market. textcite:kahlen15_aggreg_elect_cars_sustain_virtual_power_plant state
that in 42% to 80% of the time EVs are /not/ committed to a VPP when it would have been
profitable (i.e. the EV has not been rented out).

# NOTE: Section Short summary what we will do
We are proposing a solution, in which the EV fleet participates on the balancing
market and intraday market simultaneously. With this approach we aim to align
the potentially higher profits on the balancing markets with the more accurate
capacity estimations, which can be made on intraday markets (because time
between commitment and delivery is smaller). We follow
textcite:kahlen15_aggreg_elect_cars_sustain_virtual_power_plant with this
approach, who also propose a combination of multiple markets in future work on
this topic.

** Reinforcement Learning in Smart Grids

Previous research showed that intelligent agents equipped with Reinforcement
Learning methods can successfully take action in the smart grid.
textcite:reddy11_strat,reddy11_learn_behav_multip_auton_agent conducted
research, in which autonomous broker agents parencite:ketter13_power_tac learn
their strategies using RL. textcite:peters13_reinf_learn_approac_to_auton build
on that work and further enhance the method, by learning over larger state
spaces to accommodate arbitrary economic signals. This is especially beneficial
in smart markets, because the markets structures might change in the future and
intelligent agents should adapt to a variety of market structures and
conditions.

parencite:vazquez-canteli19_reinf_learn_deman_respon


textcite:valogianni14_effec_manag_elect_vehic_storag adopt RL methods to learn
electricity consumption behavior of households. The authors implement these
methods in intelligent agents to smart charge EVs more effectively.
textcite:vandael15_reinf_learn_heuris_ev_fleet use RL to learn collective EV
fleet charging behavior to profitably purchase electricity on the day-ahead
market. We consider RL a perfect fit for the design of our proposed intelligent
agent, especially as a solution for our Research Question 2. When dynamically
optimizing the VPP portfolio composition of the fleet, there is no historical
data available to train a model. Using RL and a reward function that maximizes
the overall profitability of the fleet, the agent can learn from its environment
with unknown dynamics and take a certain set of actions. The agent can consider
different states (e.g. current and forecasted rental demand levels and
electricity prices) to take actions (e.g. allocate battery capacity to different
types of VPPs) that maximizes the reward function.

* Theoretical Background (10%)
** Electricity Markets
*** Balancing Market
# parencite:brandt17_evaluat_busin_model_vehic_grid_integ has a good section
# explaining the markets.
*** Spot Market
** Reinforcement Learning
*** Notation
# NOTE: State set for every single quantity used.
The input to the network $x \in \mathbb{R}^D$ is fed to the first residual layer to get the activation $y = x + \sigma(w x + b) \in \mathbb{R}^D$ with $w \in \mathbb{R}^{D \times D}$, and $b \in \mathbb{R}^D$ the weights and bias of the layer.
*** Markow Decision Processes
*** Q-Learning
*** Function Approximation
*** Exploitation-Exploration Tradeoff
*** Deep Reinforcement Learning
* Empirical Setting / Data (10%)
** Carsharing Fleets of Electric Vehicles
# Car2Go FourTwo assumptions:
# https://www.mobilityhouse.com/de_de/elektroautos/smart/smart-eq-fortwo.html#smart-eq-fortwo-ladeinformationen


# - 17.6 Kwh battery capacity
# - 140km reach with fully charged battery

# - 3.3 (!) KW Charging capacity
# - 6h to fully charge at 4.6KW (Non-linear charging)
# - Introduced 2012, 450, later 50 more (see wiki)
# - Third Gen Smart ForTwo electric
*** Raw Data
The dataset consists of 500 EVs in Stuttgart. As displayed in Table
ref:car2go-sample-data, the data contain spatio-temporal attributes, such as
timestamp, coordinates, and address of the EVs. Additionally, status attributes
of the interior and exterior are given, the relative state of charge and
information whether the EV is plugged into one of the 200 charging stations in
Stuttgart.

#+CAPTION: Raw Car2Go Trip Data from Stuttgart label:car2go-sample-data
#+ATTR_LATEX: :environment longtable :align l|ccccc
|--------------+----------+-----------+---------------------+----------+-----------------|
|--------------+----------+-----------+---------------------+----------+-----------------|
| Number Plate | Latitude | Longitude | Street              | Zip Code | Engine Type     |
|--------------+----------+-----------+---------------------+----------+-----------------|
| S-GO2471     | 9.19121  | 48.68895  | Parkplatz Flughafen | 70692    | electric        |
| S-GO2471     | 9.15922  | 48.78848  | Salzmannweg 3       | 70192    | electric        |
| S-GO2471     | 9.17496  | 48.74928  | Felix-Dahn-Str.45   | 70597    | electric        |
| S-GO2471     | 9.17496  | 48.74928  | Felix-Dahn-Str.45   | 70597    | electric        |
| S-GO2471     | 9.17496  | 48.74928  | Felix-Dahn-Str.45   | 70597    | electric        |
|--------------+----------+-----------+---------------------+----------+-----------------|
| Number Plate | Interior | Exterior  | Timestamp           | Charging | State of Charge |
|--------------+----------+-----------+---------------------+----------+-----------------|
| S-GO2471     | good     | good      | 22.12.2017 20:10    | no       | 94              |
| S-GO2471     | good     | good      | 24.12.2017 23:05    | no       | 72              |
| S-GO2471     | good     | good      | 26.12.2017 00:40    | yes      | 81              |
| S-GO2471     | good     | good      | 26.12.2017 00:45    | yes      | 83              |
| S-GO2471     | good     | good      | 26.12.2017 00:50    | yes      | 84              |
|--------------+----------+-----------+---------------------+----------+-----------------|
|--------------+----------+-----------+---------------------+----------+-----------------|
*** Preprocessing Steps
** Electricity Markets Data
*** Secondary Operating Reserve Market
# - Relax 1 MW minimum bidding assumption
#   - 500kw
#   - 100kw
*** Intraday Continuous Spot Market

* Model: FleetRL (20%)
** Information Assumptions
# See: parencite:mashhour11_biddin_strat_virtual_power_plant_1
** Mobility Demand & Clearing Price Prediction
** Reinforcement Learning Approach
** Bidding Strategy

* Evaluation (30%)
** Event-based Simulation
** Benchmark: Ad-hoc Strategies
# - Decision Tree like models
# - Metric: Peak-to-average (PAR) ratio reduction.
** FleetRL
** Sensitivity Analysis: Prediction Accuracy
** Sensitivity Analysis: Infrastructure Changes
** Sensitivity Analysis: Bidding Strategy
* Discussion (5%)
** Generalizability
** Future Electricity Landscape
** Limitations
# - See parencite:vazquez-canteli19_reinf_learn_deman_respon conclusion for
#   limitations in RL.
* Conclusion (5%)
** Contribution
# TODO: Compare to most simular studies.
# parencite:kahlen18_elect_vehic_virtual_power_plant_dilem,vandael15_reinf_learn_heuris_ev_fleet etc..
** Future Research



#+LATEX: \clearpage
#+LATEX: \printbibliography
* Footnotes

[fn:1] citetitle:energiewende2010, cite:energiewende2010.

[fn:2] https://www.car2go.com

[fn:3] https://www.epexspot.com

[fn:4] https://www.regelleistungen.net

[fn:5] NEG-NT = Negative secondary control reserve to be provided between 00:00h and 08:00h and between 20:00h and 24:00h.

POS-HT = Positive secondary control reserve to be provided between the hours of 08:00h and 20:00h.

[fn:6] Capacity prices are in given in
#+LATEX: \euro{}/MW.

[fn:7] Energy prices are in given in
#+LATEX: \euro{}/MWh.

[fn:8] Capacities are given in MW.

[fn:9] https://procom-energy.de/

[fn:10] Unit prices are given in
#+LATEX: \euro{}c/MWh.

[fn:11] Quantities are given in kW.

[fn:12] Products: are: H = Hourly, Q = Quarterly and B = Block.

