#+TITLE: Reinforcement Learning Portfolio Optimization of Electric Vehicle Virtual Power Plants
#+AUTHOR:Tobias Richter

#+INCLUDE: "./header.org"
#+INCLUDE: "./chapters/introduction.org"
#+INCLUDE: "./chapters/background.org"
#+INCLUDE: "./chapters/empirical-setting.org"
#+INCLUDE: "./chapters/model.org"
#+INCLUDE: "./chapters/results.org"

* Conclusion
# NOTE 5%
# NOTE Sec: Setting
Integrating volatile renewable energy sources into the electricity system
imposes challenges on the electricity grid. In order to ensure grid stability
and avoid blackouts, balancing power is needed to match electricity supply and
demand. Balancing power can be provided by VPPs that generate or consume energy
within a short period of time and offer these services on the electricity
markets cite:pudjianto07_virtual_power_plant_system_integ. EV fleet operators
can utilize idle vehicles to form VPPs and offer available EV battery capacity
as balancing power to the markets. The fleet can offer balancing services
directly via tender auctions on the balancing market or via continuous trades on
the intraday market, where participants procure or sell energy to self-balance
their portfolios cite:pape16_are_fundam_enoug. Both markets have complementary
properties in terms of price levels and lead times to delivery, which motivates the
creation of a VPP portfolio to profitably participate in both markets and extend
the business model of the fleet.

# NOTE Sec: Problem
# NOTE Mention risks? Mention portfolio (optimization)?
However, there are certain risks associated  with this business model extension.
EVs can only be allocated to a VPP portfolio if they are connected to a charging
station and have sufficient free battery capacity available, information which
is unknown to the fleet at the time of market commitment. This uncertainty makes
it difficult for fleet operators to estimate the size of the VPP and calculate
the optimal bidding quantities. Moreover, if fleet operators offer more
balancing power than they can provide, they face high imbalance penalties from
the markets. For a sustainable business model fleet operators also need to
balance VPP activities with their primary offering, customer mobility. Denying
customer rentals to ensure that the fleet can fulfill the market commitments,
results in opportunity costs of lost rentals that compromise the profitability
of the fleet.

In the following chapter, we will summarize the conducted research of this
thesis to address the aforementioned challenges. Furthermore, the contribution
of this work is outlined and the main results are presented and discussed.
Finally, we list specific limitations of this study and give insights on further
areas of research.
** Contribution
# NOTE Sec: What we have done
#     1. Model (Control mechanism)
#     2. Simulation Platform
#     3. Integrated bidding strategy
#     4. RL Agent that optimizes strategy by determining risk
The core contributions of this thesis are the following: First, we
conceptualized a DSS for controlled EV charging under uncertainty. The DSS
constitutes the core of a business model extension for fleet operators to manage
a VPP portfolio of EV batteries. A controlled charging problem has been
mathematically formulated and a control mechanism introduced that aims solve the
proposed problem. Second, we developed an event-based simulation platform that
facilitates fleet management research based on real-world data. We evaluated
various baseline bidding strategies within the simulation platform and tested
out the behavior of intelligent agents in the context of controlled EV charging.
Third, we proposed a novel integrated bidding strategy that offers balancing
services of a VPP portfolio to multiple electricity markets simultaneously.
Instead of submitting only conservative amounts of battery capacity to a single
market, like previous studies did
cite:kahlen18_elect_vehic_virtual_power_plant_dilem,kahlen17_fleet, our proposed
strategy aims to maximize profits by procuring electricity from the multiple
markets to the greatest extent possible without causing imbalances. Forth, we
proposed the usage of a RL agent that learns to optimize the composition of the
VPP portfolio and the associated risks. The agent dynamically determines the
risks of bidding on the markets, depending available and predicted fleet
information. Therefore, a MDP has been defined and designed to work in
previously unknown environments and uncertain conditions. We designed the RL
agent with the focus on real-world applicability, generalizability and fast
convergence rates. We expect the proposed approach to work with a variety of
different EVs (e.g., electronic bikes) and independent of the fleets
geographical location.

# - not limited to the training data set

# - obtained better results than similar studies in the
# field. (how much and which?)

# TODO: Double check numbers!
We evaluated the proposed method with real-world carsharing data from Car2go in
Stuttgart and German electricity market data from June 2017 till January 2018.
The results show that our approach would increase the gross profits of the EV
fleet by roughly 78 000 $\eur$ over the 1.5 year period. Free float carsharing

At the same time the VPP activities have an environmental impact by reducing
CO_2 through more efficient use of renewables.

# Insights:
# - RL works good
# - Prediction is important

# NOTE Sec: What we have found
- What we have shown/found (include key numbers)
  - 1. RQ
    - Integrated improves existing approaches
    - Mitigate risk & improve profits through exploitation of different market setups
  - 2. RQ
    - RL Algorithm that
    - Online learning algorithm (difference? -- real data?)
    - RL can learn to dynamically adjust bidding quantities by learning risk
      associated with bidding on each market. (What are the risks?)
    - RL Architecture/Advancements matters
    - RL takes a long time to learn
    - Charging infrastructure & Advancement in battery technology/charging
       technology matters

# NOTE Sec: Discuss !
Discuss:
- In free float carsharing, mobility demand patterns are extremely uncertain.
  $\rightarrow$ lower bound.

- Compare to other studies!
  - Fleet Charging
    - No uncertainty
    - Only one market
    - No sensitivity on accuracy prediction (We found very important)
  - RL
  - Other approaches (VPP, stochastic)
       cite:kahlen18_elect_vehic_virtual_power_plant_dilem (no imbalance costs!)
       cite:vandael15_reinf_learn_heuris_ev_fleet

- Discuss results?
  - Gross profits small - Mention before?
  - Policy
  - Investment
  - V2G?
  - Market Setup


** Limitations
# We don't take market dynamics into account
# # NOTE: Citatation from kahlen
# The fleet controller offers bids and asks for every time interval. These offers
# contain both a quantity and a reservation price, which depends on the state of
# charge of the EV storage, as well as on the battery costs. However, the market
# may or may not accept these offers depending on the composition of the offer
# prices from the fleet owner and other market participants. The market auction
# mechanism ultimately decides when EVs will charge and discharge.

- Model:
  - Bidding Mechanism: one week ahead, always accepted
  - Policy & Regulation: EVs not allowed to provide balancing power, minimum
    bidding quantities 1MW.
  - Markets: Fleet is a price-taker, what about larger fleets? Simulate market influence
  - Deny rentals only in the same market period (More deny, less imbalance)
- RL: See cite:vazquez-canteli19_reinf_learn_deman_respon conclusion for
  limitations.
  - Training time in real time. Generalization to other cities?
** Future Research

- Model:
    - Investigate modern/current market design, that changed their bidding
      mechanisms to to better integrate renewable energy generators.
      - Daily/Day-ahead tenders with 4 hour market periods.

      Mischpreisverfahren

       i.e. daily w/ 4h slots. German "Mischpreisverfahren"
- RL: Long-delayed rewards, different reward structure, memory based
- Prediction Algorithms improvement, reference to sensitivity analysis

#+LATEX: \clearpage
#+LATEX: \appendix
* Appendix: Data Tables label:app-data-tables
#+LATEX: \renewcommand\thetable{\thesection.\arabic{table}}
#+LATEX: \setcounter{table}{0}

#+LATEX: {\captionsetup[table]{aboveskip=0.5cm}
#+CAPTION: List of Trades of the EPEX Spot Intraday Continuous Market
#+ATTR_LATEX: :float sideways :align c|cccccccc :placement [hp]
|---------------------+---------+------------+----------+------------+-------------+---------+---------------+---------------|
|---------------------+---------+------------+----------+------------+-------------+---------+---------------+---------------|
| Execution time      |      ID | Unit Price | Quantity | Buyer Area | Seller Area | Product | Product Time  | Delivery Date |
|---------------------+---------+------------+----------+------------+-------------+---------+---------------+---------------|
| 2017-12-04 06:54:55 | 8031392 |      51.00 |     5500 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:26 | 8031391 |      59.00 |    10000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:26 | 8031390 |      58.90 |    10000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:15 | 8031389 |      52.30 |     7000 | 50Hertz    | 50Hertz     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:13 | 8031386 |      59.00 |      500 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:13 | 8031387 |      51.00 |     3600 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:13 | 8031388 |      52.00 |     1400 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:53:02 | 8031385 |      58.90 |    11000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:38 | 8031380 |      60.00 |    10000 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:38 | 8031381 |      57.50 |     8000 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:38 | 8031382 |      58.00 |     2000 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:38 | 8031383 |      58.90 |     4000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:38 | 8031384 |      60.00 |     4000 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:52:27 | 8031379 |      52.30 |     8000 | 50Hertz    | 50Hertz     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:51:33 | 8031378 |      66.00 |     5000 | TransnetBW | TransnetBW  | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:51:28 | 8031377 |      54.00 |     8000 | Amprion    | Amprion     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:51:24 | 8031376 |      54.00 |     7000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:49:34 | 8031375 |      51.00 |     4000 | TenneT     | TenneT      | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:49:26 | 8031374 |      54.00 |     5000 | 50Hertz    | 50Hertz     | Quarter | 07:15 - 07:30 |    2017-12-04 |
| 2017-12-04 06:49:23 | 8031373 |      55.10 |     8000 | 50Hertz    | 50Hertz     | Quarter | 07:15 - 07:30 |    2017-12-04 |
|---------------------+---------+------------+----------+------------+-------------+---------+---------------+---------------|
|---------------------+---------+------------+----------+------------+-------------+---------+---------------+---------------|
#+LATEX:}
#+LATEX: \clearpage

* Appendix: Data Preprocessing label:app-data-processing
The raw Car2Go dataset contained about 63 million data points (7.82 GB) and has
been processed to only contain about 1.25 thousand data points (100 MB), while
still compromising all necessary information. The following preprocessing steps
have been taken to prepare the data for further analysis:

1) Determine rental trips

   Rental trips were inferred based on changing GPS coordinates between two data
   points of the same EV (see Table ref:table-car2go-raw, 4^{th} to 5^{th} row).
   Since the GPS accuracy of industry sensors is approximately 5 meters under
   open sky, and worse near buildings, bridges, and trees[fn:5], measurement
   errors occur. To reduce the number of falsely identified trips, a decreased
   resolution of a 10-meter radius was calculated. Note that we hereby assume
   that customers do not undertake trips, which begin and end at the same
   location. In total, 1246040 customer rentals were determined.

2) Determine trip distances

   The trip distances were inferred based on the difference in SoC level before
   and after the rental and the average energy consumption per kilometer.
   Although the real distance that can be covered with a certain amount of
   energy depends on driving style and traffic situation, we are confident that
   the deviation will be small, since all trips take place within the same urban
   space.

3) Determine rental profits

   The rental profits were inferred based on the trip duration and the estimated
   trip distance. Car2Go has a minutely pricing scheme with an additional long
   distance fee that applies when the customer drives more than a specified
   range. The rental profits form an important piece of information for our
   model since they determine the opportunity cost $\rho$ the fleet controller
   has to account for if it denies the rental in favor of VPP activities.

4) Clean data
   - /Service trips/: 3308 rental trips were removed that had a trip duration
     longer than the maximum allowed rental time of two days. We assume that
     these trips were /service trips/ undertaken by Car2Go. When the EVs
     returned with a higher SoC (e.g., they have been charged at the car repair
     shop), the previous trip had to be altered to end at a charging station to
     ensure charging consistency.
   - /Incorrectly charged EVs/: 52 EVs were removed that showed incorrect
     charging behavior. These EVs reported a battery level increase of more than 20%
     between trips or during trips, while not being located at a charging station.

#+LATEX: \clearpage
* Appendix: DDQN Hyperparameters label:app-rl-hyperparams
#+LATEX: \setcounter{table}{0}
#+CAPTION[Hyperparameters for the dueling network DDQN algorithm]: Hyperparameters for the dueling network DDQN algorithm.
#+ATTR_LATEX: :environment longtable :align lr :placement [hp]
|--------------------------------+--------------------------------------|
|--------------------------------+--------------------------------------|
| Hyperparameter                 |                                Value |
|--------------------------------+--------------------------------------|
| Target network update interval |                                 0.01 |
| Optimizer                      |              Adam cite:kingma14_adam |
| Batch size                     |                                   32 |
| Learning rate                  |                              10^{-3} |
| Replay buffer size             |                                 10^5 |
| Warm-up steps                  |                                 1000 |
| Training steps                 |                                 10^5 |
| Discount factor $\gamma$       |                                 0.99 |
| Reward normalization           |                      r $\in$ [-1, 1] |
| Gradient clipping              | Gradient in [-1, 1] for output layer |
| Network architecture           |      See Appendix ref:rl-network-def |
|--------------------------------+--------------------------------------|
| \epsilon-greedy annealing      |               Linear over 10^5 steps |
| \epsilon-greedy minimum value  |                                  0.1 |
|--------------------------------+--------------------------------------|
|--------------------------------+--------------------------------------|
#+LATEX: \clearpage
* Appendix: DDQN Network Definition label:rl-network-def

#+INCLUDE: "./template/keras.tex" export latex

#+LATEX: \clearpage
bibliography:~/uni/ma-thesis/bibliography/references.bib
bibliographystyle:apacite
* Footnotes

[fn:1] https://pypi.org/project/simpy/

* Footnotes

[fn:5] See https://www.gps.gov/systems/gps/performance/accuracy, accessed
23^{th} February 2019.
