* Literature Review
** Electric Vehicles, Virtual Power Plants, V2G
- Avci et al. (2015) - Electric vehicles with a battery switching station: Adoption and environmental impact
  - Infrastructure and positioning aspects
- Fridgen et al. (2014) - The value of information exchange in electric vehicle charging
  - Customer sharing information leads to better utilization
- He et al. (2016) - Optimal bidding strategy of battery storage in power markets considering performance-based regulation and battery cycle life
  - Stationary storage
  - Multiple energy market bidding at the same time(!)
  - Battery degradation
- Kara et al. (2015) - Estimating the benefits of electric vehicle smart charging at non-residential locations: A data-driven approach
  - Intelligent Scheduling
- Kim et al. (2012) - Carbitrage: Utility integration of electric vehicles and the smart grid
  - Grid stability
- Mak et al. (2013) - Infrastructure planning for electric vehicles with battery swapping
  - Infrastructure and positioning aspects
- Mashour and Moghaddas-Trafreshi (2011) - Bidding strategy of virtual power plant for participating in energy and spinning reserve markets
  - Stationary storage
  - Energy and Reserve Market bidding at the same time (!)
- Peterson et al. (2010) - The economics of using plug-in hybrid electric vehicle battery packs for grid storage
  - V2G
- Sioshansi (2012) - EV demand on Grid stability
  - EVs offer balancing services to the grid (operating reserve, balancing market)
- Vytelingum et al. (2011) - Static storage capacity in households, dynamic pricing
  - EVs offer balancing services to the grid (operating reserve, balancing market)
** DSS, Intelligent Agents, State of the Art ML Techniques
- Kahlen et al. (2017) - Electric Vehicle Virtual Power Plant Dilemma: Grid Balancing Versus Customer Mobility
- Kahlen et al. (2017) - Fleetpower: Creating virtual power plants in sustainable smart electricity markets
- Avci et al. (2018) - Managing electricity price modeling risk via ensemble forecasting: The case
of Turkey
 - Ensemble Forecasting: Time-series models, Seasonality models, Artificial
   Neural Networks
- Peters, Markus, et al. "A reinforcement learning approach to autonomous decision-making in smart electricity markets." Machine learning 92.1 (2013): 5-39. Ketter et al. (2016) - MISQ Competitive Benchmarking
** Carsharing (?)
- Firnkorn and Mueller (2011) - Free-Float Carsharing Environmental effects
** More Papers
*** Main Papers
- Bichler, Martin, Alok Gupta, and Wolfgang Ketter. "Research commentary—designing smart markets." Information Systems Research 21.4 (2010): 688-699.- Brand et al. (2017)
- Flath et al. (2013) - Area pricing
- Pudjianto et al. (2017) -
- Reichert (2010) - V2G, battery degradation costs
- Schill (2011)
- Tomic and Kempton (2007) - V2G profitability dependent on market setup
- Valogianni et al. (2014) - Smart charging w/ price incentives
- Wagner et al. (2016) - Smart charging w/ price incentives
- Wolfson et al. (2011) - Battery swapping infrastructure
- Zhou et al. (2015) - Stationary storage, dynamic pricing, industrial setting
*** Touching Papers and Conference Papers
- Kahlen et al. (2014) - ECIS Conference Paper: Balancing with EVs - Simulation PowerTac?
- Kahlen and Ketter (2015) - AI Conference Paper: Fleetpower
- Kahlen et al. (2017) - Hawai System Science Conference Paper
- Ketter et al. (2013) - Power Tac Smart Grid
- Ketter et al. (2016) - MISQ Powertac
