#+TITLE: Portfolio Optimization of Electric Vehicle Virtual Power Plants in Smart Sustainable Electricity Markets: A ML-based Intelligent Agent Approach
#+SUBTITLE: Master Thesis Proposal
#+AUTHOR:Tobias Richter
#+LATEX_HEADER: \usepackage[margin=1.5in]{geometry}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \onehalfspacing
#+OPTIONS: H:4

* Introduction
** Research Motivation

- C0^2 emissions need to be reduced.
- Transition to sustainable energy sources is a wicked problem.
- Electric Vehicles powered by renewable energy sources is a needed measure to
  reduce emissions.
- Integration of renewables into the energy grid is difficult. Exogenous
  factors like sun and wind make them highly intermittent and thus hard to
  integrate into a power grid, which has to be balanced at all times.
- Carsharing companies have centrally managed EV fleets at their hands that can be
  turned into Virtual Power Plants (VPP). VPPs can be used to balance out excess
  electricity or electricity insufficiency from the grid.
- Using VPPs allows carsharing fleets to profitably act on electricity
  markets. Buying electricity (charge EVs), when prices are low (excess energy) and
  selling electricity (discharge EVs, V2G), when prices are high (energy insufficiency).
- But: The usage of EVs as VPP compromises customer mobility and profitability of
  the fleet.
- Thus: An intelligent Agent is needed, which dynamically allocates parked, plugged-in EVs to be
  used as VPP or stay idle, depending whether an EV is likely going to be rented out and how much
  capacity it has available.
- It is possible to act not only on one electricity market, but on multiple:

  *Operating reserve markets* offer higher profits, due to a very low reaction time
  between contractual agreement and physical delivery. They also bear a higher risk for the
  fleet. Commitments have to be made one week in advance, where customer demands
  are uncertain. To not face penalties for unfulfilled commitments, only a
  conservative estimation of available battery capacity can be made. This leaves
  a lot of potential EV capacity unused.

  *Continuous intraday markets* allow participants to continuously trade electricity products up
  to 15 minutes prior to delivery (in Germany). At this point it is possible to
  predict customer demand with a high accuracy, which generates the possibility
  to trade the remaining available capacity with a low risk.

** Research Question (!)

1. Accurate forecasting of spatio-temporal customer demand patterns of carsharing EVs:
   Predict available battery capacity of EV fleets.

2. Dynamically learn the optimal allocation ratio of EVs to operating reserve
   VPPs and intraday VPPs using a recurrent neural network approach.

3. Develop an intelligent agent that autonomously acts on operating reserve and
   day-ahead electricity markets with and integrated bidding strategy.

** Relevance of the Research
*** Relevance to Science
- Dynamically optimize the allocation of EVs to different types of VPP using
  recurrent neural networks.
- In the context of EV VPPs an integrated bidding strategy to ac
- Application and comparison of Advanced ML Models (for spatial time-series forecasting)
*** Relevance to Practice

- An intelligent agent will be developed, which can be used by carsharing
  providers to dynamically allocate EVs of their fleet to VPPs on different
  electricity markets. The agent will predict available capacity and auction
  prices to profitably act on the operating reserve and continuous intraday
  market. The profitability will be evaluated using real-world data from German
  electricity markets.

*** Relevance to Society
- Grid stability through balancing
- Integration of more renewable sources into the energy grid
* Empirical Setting
- Describe relevance and mechanisms of car-sharing and electricity market auctions
- Show excerpts of the available data and explain.
** Carsharing Fleets
- Car2Go: Berlin
- Use same time span for car data as respective market data (!?)
** Electricity Markets
- Epex Spot Market: Continuous intraday trading data from 2016-2017.
- Secondary reserve market data from Germany (https://regelleistung.net)
* Literature Review
** Electric Vehicles, Virtual Power Plants, V2G
- Avci et al. (2015) - Electric vehicles with a battery switching station: Adoption and environmental impact
  - Infrastructure and positioning aspects
- Fridgen et al. (2014) - The value of information exchange in electric vehicle charging
  - Customer sharing information leads to better utilization
- He et al. (2016) - Optimal bidding strategy of battery storage in power markets considering performance-based regulation and battery cycle life
  - Stationary storage
  - Multiple energy market bidding at the same time(!)
  - Battery degradation
- Kara et al. (2015) - Estimating the benefits of electric vehicle smart charging at non-residential locations: A data-driven approach
  - Intelligent Scheduling
- Kim et al. (2012) - Carbitrage: Utility integration of electric vehicles and the smart grid
  - Grid stability
- Mak et al. (2013) - Infrastructure planning for electric vehicles with battery swapping
  - Infrastructure and positioning aspects
- Mashour and Moghaddas-Trafreshi (2011) - Bidding strategy of virtual power plant for participating in energy and spinning reserve markets
  - Stationary storage
  - Energy and Reserve Market bidding at the same time (!)
- Peterson et al. (2010) - The economics of using plug-in hybrid electric vehicle battery packs for grid storage
  - V2G
** DSS, Intelligent Agents, State of the Art ML Techniques
- Kahlen et al. (2017) - Electric Vehicle Virtual Power Plant Dilemma: Grid Balancing Versus Customer Mobility
- Kahlen et al. (2017) - Fleetpower: Creating virtual power plants in sustainable smart electricity markets
** Carsharing (?)
- Firnkorn and Mueller (2011) - Free-Float Carsharing Environmental effects
** Auction Theory (?)
** More Papers
**Main Papers**
- Brand et al. (2017)
- Flath et al. (2013) - Area pricing
- Pudjianto et al. (2017) -
- Reichert (2010) - V2G, battery degradation costs
- Schill (2011)
- Sioshansi (2012) - EV demand on Grid stability
- Tomic and Kempton (2007) - V2G profitability dependent on market setup
- Valogianni et al. (2014) - Smart charging w/ price incentives
- Vytelingum et al. (2011) - Static storage capacity in households, dynamic pricing
- Wagner et al. (2016) - Smart charging w/ price incentives
- Wolfson et al. (2011) - Battery swapping infrastructure
- Zhou et al. (2015) - Stationary storage, dynamic pricing, industrial setting

**Touching Papers and Conference Papers**
- Kahlen et al. (2014) - ECIS Conference Paper: Balancing with EVs - Simulation PowerTac?
- Kahlen and Ketter (2015) - AI Conference Paper: Fleetpower
- Kahlen et al. (2017) - Hawai System Science Conference Paper
- Ketter et al. (2013) - Power Tac Smart Grid
- Ketter et al. (2016) - MISQ Powertac
- Ketter et al. (2016) - MISQ Competitive Benchmarking
* Research Design
** Methodology (!)
*** Quantitative Study
- What is the purpose of the study?
  1. EV Capacity Prediction / Demand Prediction
  2. Determine Bids/Asks/Market: Price Prediction
- Mention Algorithms?
  - Type of models or already detailed?
  - Too early in proposal when focus is on ML?
*** Event-based simulation
*** ML-based Intelligent Agents
* Expected Contribution
* Research Plan (Also for MA Thesis?)
- 6 Month plan?
- Another test

* Wolf Requirements
** MA Proposal

- The proposal depicts the main background and motivation of your research topic.
- Based on the proposal, a concise research question is to be derived and formulated.
- The methodological approach shall be outlined.
- The suggested methods and algorithms shall be listed.
- Please give an overview on the respective data.
- The proposal already has to include relevant literature references.
- Please note that special focus shall be placed on the research question and the respective approach.
 cite:mehta14_ident_poten_bo2_oxide_polym



** PhD Proposal
- Specially attention is paid to related work, data, methods, and analysis, and potential contribution/conclusion.



bibliography:proposal.bib
